package com.mytech.backend.portal;

import com.mytech.backend.portal.models.Dish;
import com.mytech.backend.portal.repositories.DishRepository;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

@SpringBootTest
public class DishDataSeederTest {

    @Autowired
    private DishRepository dishRepository;

    @Test
    void seedDishes() {
        List<Dish> dishes = new ArrayList<>();

        // ================== 🥗 APPETIZER (50 món) ==================
        dishes.addAll(Arrays.asList(
            new Dish(null, "Gỏi cuốn tôm thịt", "Gỏi cuốn tôm thịt tươi ngon chấm mắm nêm", 45000, 100, "/uploads/1758565332469_A-goi_cuon_tom_thit.jpeg", "APPETIZER", "AVAILABLE"),
            new Dish(null, "Nem rán Hà Nội", "Nem rán giòn rụm, nóng hổi, chấm tương ớt", 55000, 80, "/uploads/1758565415978_A-nem_ran_ha_noi.jpeg", "APPETIZER", "AVAILABLE"),
            new Dish(null, "Chả giò hải sản", "Chả giò nhân tôm, mực, cua, giòn tan", 60000, 75, "/uploads/1758567070896_A-cha_gio_hai_san.jpeg", "APPETIZER", "AVAILABLE"),
            new Dish(null, "Salad trộn dầu giấm", "Salad tươi mát với rau xanh, cà chua, dưa chuột", 40000, 90, "/uploads/1758567085670_A-salad_tron_dau_giam.jpeg", "APPETIZER", "AVAILABLE"),
            new Dish(null, "Nộm bò khô", "Nộm đu đủ với thịt bò khô, lạc rang", 65000, 60, "/uploads/1758567096404_A-nom_bo_kho.jpeg", "APPETIZER", "AVAILABLE"),
            new Dish(null, "Salad cá ngừ", "Cá ngừ hộp trộn salad, giàu protein", 55000, 50, "/uploads/1758567109437_A-salad_ca_ngu.jpeg", "APPETIZER", "AVAILABLE"),
            new Dish(null, "Súp bí đỏ", "Súp bí đỏ thơm ngon, béo ngậy, tốt cho sức khỏe", 50000, 45, "/uploads/1758567119819_A-sup_bi_do.jpeg", "APPETIZER", "AVAILABLE"),
            new Dish(null, "Súp hải sản", "Súp tổng hợp tôm, mực, nghêu, ngọt thanh", 65000, 55, "/uploads/1758567130675_A-sup_hai_san.jpeg", "APPETIZER", "AVAILABLE"),
            new Dish(null, "Súp gà nấm hương", "Súp gà với nấm hương, rau củ", 60000, 65, "/uploads/1758567141775_A-sup_ga_nam_huong.jpeg", "APPETIZER", "AVAILABLE"),
            new Dish(null, "Bánh mì bơ tỏi", "Bánh mì nướng với bơ và tỏi, thơm lừng", 35000, 120, "/uploads/1758567153174_A-banh_my_bo_toi.jpeg", "APPETIZER", "AVAILABLE"),
            new Dish(null, "Bánh xèo mini", "Bánh xèo giòn, nhân tôm, thịt, giá đỗ", 45000, 70, "/uploads/1758567169035_A-banh_xeo_mini.jpeg", "APPETIZER", "AVAILABLE"),
            new Dish(null, "Gỏi ngó sen tôm thịt", "Gỏi ngó sen giòn, tôm thịt đậm đà", 60000, 65, "/uploads/1758567180378_A_goi_ngo_sen_tom_thit.jpeg", "APPETIZER", "AVAILABLE"),
            new Dish(null, "Salad Caesar", "Salad với sốt Caesar đặc trưng, thịt gà nướng", 65000, 50, "/uploads/1758567196043_A-Salad_Caesar.jpeg", "APPETIZER", "AVAILABLE"),
            new Dish(null, "Chả cá chiên", "Chả cá chiên từ cá tươi, dai ngon", 50000, 60, "/uploads/1758567209902_A-cha_ca_chien.jpeg", "APPETIZER", "AVAILABLE"),
            new Dish(null, "Súp cua", "Súp cua nóng hổi, thanh mát", 55000, 55, "/uploads/1758567221299_A-sup_cua.jpeg", "APPETIZER", "AVAILABLE")
//            new Dish(null, "Nem chua rán", "Nem chua rán giòn, ăn kèm tương ớt", 45000, 80, "https://example.com/images/nem_chua_ran.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Bánh khọt", "Bánh khọt giòn với nhân tôm, ăn kèm rau sống", 50000, 70, "https://example.com/images/banh_khot.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Gỏi bưởi tôm thịt", "Gỏi bưởi chua ngọt, tôm thịt", 60000, 50, "https://example.com/images/goi_buoi.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Khoai tây chiên bơ tỏi", "Khoai tây chiên giòn rụm với bơ và tỏi", 40000, 100, "https://example.com/images/khoai_tay_bo_toi.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Salad trái cây", "Hỗn hợp trái cây tươi, sữa chua", 50000, 75, "https://example.com/images/salad_trai_cay.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Nộm sứa", "Nộm sứa giòn, kết hợp rau củ tươi", 60000, 45, "https://example.com/images/nom_sua.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Súp măng tây cua", "Súp măng tây béo ngậy, ngọt thịt cua", 65000, 50, "https://example.com/images/sup_mang_tay.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Nem cuốn thịt nướng", "Nem cuốn với thịt nướng, rau sống, bún", 55000, 60, "https://example.com/images/nem_cuon_thit_nuong.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Súp gà ngô non", "Súp gà với ngô non, ngọt thanh", 50000, 55, "https://example.com/images/sup_ga_ngo.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Salad bơ trứng", "Salad với bơ, trứng, sốt mayo", 55000, 60, "https://example.com/images/salad_bo_trung.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Bánh bao chiên", "Bánh bao chiên giòn, nhân thịt băm", 40000, 80, "https://example.com/images/banh_bao_chien.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Bánh gối", "Bánh gối nhân thịt, trứng cút", 45000, 70, "https://example.com/images/banh_goi.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Súp kem nấm", "Súp kem béo ngậy với nấm tươi", 60000, 40, "https://example.com/images/sup_kem_nam.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Chả giò chay", "Chả giò nhân nấm, rau củ, phù hợp người ăn chay", 45000, 65, "https://example.com/images/cha_gio_chay.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Súp tôm ngô", "Súp tôm và ngô ngọt, dễ ăn", 60000, 50, "https://example.com/images/sup_tom_ngo.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Nộm rau muống thịt bò", "Nộm rau muống giòn với thịt bò xào", 50000, 55, "https://example.com/images/nom_rau_muong.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Salad dưa chuột cà chua", "Salad dưa chuột và cà chua đơn giản, thanh mát", 40000, 70, "https://example.com/images/salad_dua_ca_chua.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Gỏi xoài cá khô", "Gỏi xoài chua ngọt, thêm cá khô mặn mặn", 55000, 45, "https://example.com/images/goi_xoai.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Bánh cuốn nóng", "Bánh cuốn tráng nóng, nhân thịt mộc nhĩ", 45000, 80, "https://example.com/images/banh_cuon.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Súp lươn Nghệ An", "Súp lươn đặc trưng Nghệ An, đậm đà", 65000, 40, "https://example.com/images/sup_luon.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Gỏi cá mai", "Gỏi cá mai tươi, giòn, cuốn bánh tráng", 70000, 35, "https://example.com/images/goi_ca_mai.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Nem hải sản", "Nem cuốn với nhân hải sản, rau củ", 60000, 50, "https://example.com/images/nem_hai_san.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Salad gà xé", "Salad với thịt gà xé, sốt đặc biệt", 55000, 60, "https://example.com/images/salad_ga_xe.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Súp chua cay Thái", "Súp Tom Yum chuẩn vị Thái Lan", 65000, 45, "https://example.com/images/sup_chua_cay_thai.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Chả ốc lá lốt", "Chả ốc cuốn lá lốt nướng, thơm lừng", 70000, 40, "https://example.com/images/cha_oc.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Súp cá hồi", "Súp cá hồi nấu với rau củ tươi", 70000, 45, "https://example.com/images/sup_ca_hoi.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Salad tôm xoài", "Salad tôm tươi với xoài chua ngọt", 65000, 50, "https://example.com/images/salad_tom_xoai.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Gỏi dưa leo tôm khô", "Gỏi dưa leo giòn mát với tôm khô", 55000, 60, "https://example.com/images/goi_dua_leo.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Bánh căn trứng cút", "Bánh căn giòn, nóng, ăn kèm trứng cút", 50000, 70, "https://example.com/images/banh_can.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Súp sò điệp", "Súp sò điệp thơm ngon, bổ dưỡng", 75000, 35, "https://example.com/images/sup_so_diep.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Salad rau mầm", "Salad rau mầm tươi, giòn, tốt cho sức khỏe", 50000, 65, "https://example.com/images/salad_rau_mam.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Nem cua bể", "Nem cua bể Hải Phòng, nhân đầy đặn", 70000, 40, "https://example.com/images/nem_cua_be.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Gỏi cá trích", "Gỏi cá trích tươi ngon, đặc sản Phú Quốc", 75000, 30, "https://example.com/images/goi_ca_trich.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Súp kem hải sản", "Súp kem với các loại hải sản tươi", 75000, 40, "https://example.com/images/sup_kem_hai_san.jpg", "APPETIZER", "AVAILABLE"),
//            new Dish(null, "Bánh mì bơ tỏi phô mai", "Bánh mì nướng bơ tỏi, phủ phô mai", 45000, 90, "https://example.com/images/banh_mi_bo_toi_pho_mai.jpg", "APPETIZER", "AVAILABLE")
        ));

        // ================== 🍖 BBQ (50 món) ==================
        dishes.addAll(Arrays.asList(
            new Dish(null, "Bò Mỹ nướng tảng", "Thịt bò Mỹ nướng nguyên tảng, mềm, ngọt", 250000, 30, "/uploads/1758567664123_B-bò_nướng_tảng_1.jpeg", "BBQ", "AVAILABLE"),
            new Dish(null, "Bò cuộn nấm kim châm", "Thịt bò cuộn nấm kim châm nướng, đậm vị", 120000, 50, "/uploads/1758567655879_B_Bò_cuộn_nấm_kim_châm_2.jpeg", "BBQ", "AVAILABLE"),
            new Dish(null, "Ba chỉ heo nướng mật ong", "Ba chỉ heo ướp mật ong, nướng thơm lừng", 95000, 60, "/uploads/1758567648263_B-Ba chỉ heo nướng mật ong_3.jpeg", "BBQ", "AVAILABLE"),
            new Dish(null, "Gà nướng muối ớt", "Gà ta nướng muối ớt, da giòn, thịt dai", 115000, 45, "/uploads/1758567640482_B-Gà nướng muối ớt_4.jpeg", "BBQ", "AVAILABLE"),
            new Dish(null, "Sườn non nướng BBQ", "Sườn non heo ướp sốt BBQ, nướng than hoa", 150000, 55, "/uploads/1758567630450_B-Sườn non nướng BBQ_5.jpeg", "BBQ", "AVAILABLE"),
            new Dish(null, "Tôm nướng sa tế", "Tôm tươi nướng sa tế, cay nồng", 180000, 40, "/uploads/1758567616149_B-Tôm nướng sa tế_6.jpeg", "BBQ", "AVAILABLE"),
            new Dish(null, "Mực nướng muối ớt", "Mực ống nướng muối ớt, giòn sần sật", 170000, 35, "/uploads/1758567604521_B-Mực nướng muối ớ_7.jpeg", "BBQ", "AVAILABLE"),
            new Dish(null, "Sò điệp nướng mỡ hành", "Sò điệp nướng mỡ hành, đậu phộng", 190000, 30, "/uploads/1758567595710_B-Sò điệp nướng mỡ hành_8.jpeg", "BBQ", "AVAILABLE"),
            new Dish(null, "Hàu nướng phô mai", "Hàu tươi nướng với phô mai béo ngậy", 200000, 25, "/uploads/1758567586999_B-Hàu nướng phô mai_9.jpeg", "BBQ", "AVAILABLE"),
            new Dish(null, "Thịt xiên nướng", "Thịt xiên nướng kiểu đường phố, thơm ngon", 80000, 100, "/uploads/1758567555870_B-Thịt xiên nướng_10.jpeg", "BBQ", "AVAILABLE"),
            new Dish(null, "Bạch tuộc nướng", "Bạch tuộc tươi nướng, dai ngon", 160000, 30, "/uploads/1758567544101_B-Bạch tuộc nướng_11.jpeg", "BBQ", "AVAILABLE"),
            new Dish(null, "Thăn bò Wagyu nướng", "Thăn bò Wagyu nướng, tan chảy trong miệng", 500000, 15, "/uploads/1758567445121_B-Thăn bò Wagyu nướng_13.jpeg", "BBQ", "AVAILABLE"),
            new Dish(null, "Lòng heo nướng", "Lòng heo nướng giòn, ăn kèm kim chi", 90000, 40, "/uploads/1758567456420_B-Lòng heo nướng_13.jpeg", "BBQ", "AVAILABLE"),
            new Dish(null, "Chân gà nướng", "Chân gà nướng giòn, ướp gia vị đậm đà", 75000, 60, "/uploads/1758567565975_B-chân gà nướng_14.jpeg", "BBQ", "AVAILABLE"),
            new Dish(null, "Cá kèo nướng muối ớt", "Cá kèo nướng muối ớt, ăn kèm rau sống", 110000, 35, "/uploads/1758567576751_B-cá kèo nướng muối ớt_15.jpeg", "BBQ", "AVAILABLE")
//            new Dish(null, "Ba rọi bò nướng", "Ba rọi bò nướng, mềm, béo", 140000, 50, "https://example.com/images/ba_roi_bo.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Thịt nai nướng", "Thịt nai nướng, mềm, không dai", 180000, 25, "https://example.com/images/nai_nuong.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Sườn cừu nướng", "Sườn cừu nướng sốt, thơm ngon", 220000, 20, "https://example.com/images/suon_cuu.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Cánh gà nướng", "Cánh gà nướng sốt teriyaki", 90000, 70, "https://example.com/images/canh_ga_nuong.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Rau củ nướng", "Khoai tây, bắp, đậu bắp nướng", 60000, 80, "https://example.com/images/rau_cu_nuong.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Gà nướng lá chanh", "Gà nướng với lá chanh thơm lừng", 120000, 40, "https://example.com/images/ga_nuong_la_chanh.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Bò lúc lắc nướng", "Bò lúc lắc nướng, mềm và ngọt", 150000, 45, "https://example.com/images/bo_luc_lac.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Cá hồi nướng", "Cá hồi nướng, tốt cho sức khỏe", 200000, 30, "https://example.com/images/ca_hoi_nuong.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Cá diêu hồng nướng", "Cá diêu hồng nướng mọi", 130000, 35, "https://example.com/images/ca_dieu_hong.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Mề gà nướng", "Mề gà nướng giòn, cay", 85000, 50, "https://example.com/images/me_ga_nuong.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Lòng nướng sa tế", "Lòng nướng cay nồng", 95000, 45, "https://example.com/images/long_nuong_sa_te.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Bánh mì bơ nướng", "Bánh mì phết bơ nướng giòn", 40000, 90, "https://example.com/images/banh_mi_bo_nuong.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Tôm càng xanh nướng", "Tôm càng xanh nướng, thịt dai, ngọt", 250000, 25, "https://example.com/images/tom_cang_xanh.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Cá lóc nướng trui", "Cá lóc nướng trui, đặc sản miền Tây", 140000, 30, "https://example.com/images/ca_loc_nuong_trui.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Thịt bò nướng lá lốt", "Thịt bò nướng lá lốt thơm lừng", 130000, 50, "https://example.com/images/bo_nuong_la_lot.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Dẻ sườn bò nướng", "Dẻ sườn bò nướng mềm, ngọt", 200000, 40, "https://example.com/images/de_suon_bo.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Thịt dê nướng", "Thịt dê nướng, không hôi", 180000, 30, "https://example.com/images/de_nuong.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Thịt heo rừng nướng", "Thịt heo rừng nướng, dai ngon", 160000, 35, "https://example.com/images/heo_rung_nuong.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Thịt cừu nướng tảng", "Thịt cừu nướng nguyên tảng", 280000, 20, "https://example.com/images/cuu_nuong_tang.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Hàu nướng mỡ hành", "Hàu nướng mỡ hành, thơm béo", 190000, 40, "https://example.com/images/hau_nuong_mo_hanh.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Thịt thỏ nướng", "Thịt thỏ nướng, mềm, ngọt", 170000, 25, "https://example.com/images/tho_nuong.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Heo sữa quay", "Heo sữa quay nguyên con, da giòn", 300000, 10, "https://example.com/images/heo_sua_quay.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Ốc hương nướng", "Ốc hương nướng muối ớt", 220000, 30, "https://example.com/images/oc_huong_nuong.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Vịt nướng chao", "Vịt nướng chao, đậm đà hương vị", 150000, 35, "https://example.com/images/vit_nuong_chao.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Thịt lợn Mán nướng", "Thịt lợn Mán nướng than hoa", 180000, 40, "https://example.com/images/lon_man_nuong.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Lươn nướng", "Lươn nướng giòn, béo", 160000, 30, "https://example.com/images/luon_nuong.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Sườn bò nướng sốt Hàn", "Sườn bò nướng sốt BBQ Hàn Quốc", 210000, 45, "https://example.com/images/suon_bo_han.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Rau củ nướng sốt phô mai", "Rau củ nướng với sốt phô mai tan chảy", 70000, 50, "https://example.com/images/rau_cu_pho_mai.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Gà nướng phô mai", "Thịt gà nướng phủ phô mai", 130000, 40, "https://example.com/images/ga_nuong_pho_mai.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Cá sấu nướng", "Thịt cá sấu nướng, dai ngon", 250000, 20, "https://example.com/images/ca_sau_nuong.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Tôm sú nướng", "Tôm sú tươi nướng, thịt dai", 220000, 30, "https://example.com/images/tom_su_nuong.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Gà nướng ống tre", "Gà nướng trong ống tre, thơm đặc trưng", 150000, 25, "https://example.com/images/ga_nuong_ong_tre.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Thịt bò nướng tiêu xanh", "Thịt bò nướng tiêu xanh cay nhẹ", 180000, 35, "https://example.com/images/bo_nuong_tieu.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Sườn heo nướng riềng mẻ", "Sườn heo nướng riềng mẻ, đậm đà", 120000, 50, "https://example.com/images/suon_rieng_me.jpg", "BBQ", "AVAILABLE"),
//            new Dish(null, "Chả nướng", "Chả nướng từ thịt lợn, thơm ngon", 90000, 60, "https://example.com/images/cha_nuong.jpg", "BBQ", "AVAILABLE")
        ));

        // ================== 🍲 HOTPOT (50 món) ==================
        dishes.addAll(Arrays.asList(
            new Dish(null, "Lẩu Thái hải sản", "Lẩu Thái chua cay, hải sản tươi ngon", 350000, 20, "/uploads/1758567808560_H-lẩu thái hải sản_1.jpeg", "HOTPOT", "AVAILABLE"),
            new Dish(null, "Lẩu riêu cua bắp bò", "Lẩu riêu cua đồng, bắp bò mềm", 300000, 25, "/uploads/1758567901906_H-Lẩu dê thuốc bắc_3.jpeg", "HOTPOT", "AVAILABLE"),
            new Dish(null, "Lẩu dê thuốc bắc", "Lẩu dê thuốc bắc, bổ dưỡng", 380000, 15, "/uploads/1758568082510_H-Lẩu gà nấm_4.jpeg", "HOTPOT", "AVAILABLE"),
            new Dish(null, "Lẩu gà nấm", "Lẩu gà ta với các loại nấm tươi", 280000, 30, "/uploads/1758568092791_H-Lẩu bò nhúng giấm_5.jpeg", "HOTPOT", "AVAILABLE"),
            new Dish(null, "Lẩu bò nhúng giấm", "Lẩu bò nhúng giấm chua thanh", 320000, 20, "/uploads/1758568153141_H-Lẩu cháo lòng_5.jpeg", "HOTPOT", "AVAILABLE"),
            new Dish(null, "Lẩu cháo lòng", "Lẩu cháo lòng, thơm ngon", 250000, 15, "/uploads/1758568176916_H-Lẩu cá chép om dưa_6.jpeg", "HOTPOT", "AVAILABLE"),
            new Dish(null, "Lẩu cá chép om dưa", "Lẩu cá chép om dưa, chua ngọt", 290000, 18, "/uploads/1758568192303_H-Lẩu cá lăng_7.jpeg", "HOTPOT", "AVAILABLE"),
            new Dish(null, "Lẩu cá lăng", "Lẩu cá lăng, thịt cá dai, ngọt", 330000, 12, "/uploads/1758568232803_H-Lẩu thập cẩm_8.jpeg", "HOTPOT", "AVAILABLE"),
            new Dish(null, "Lẩu thập cẩm", "Lẩu với nhiều loại topping", 360000, 20, "/uploads/1758568241992_H-Lẩu ếch măng cay_9.jpeg", "HOTPOT", "AVAILABLE"),
            new Dish(null, "Lẩu ếch măng cay", "Lẩu ếch măng cay, đậm vị", 310000, 15, "/uploads/1758568253228_H-Lẩu cua đồng_10.jpeg", "HOTPOT", "AVAILABLE"),
            new Dish(null, "Lẩu cua đồng", "Lẩu cua đồng, vị ngọt thanh", 340000, 18, "/uploads/1758568262858_H-Lẩu mắm_11.jpeg", "HOTPOT", "AVAILABLE"),
            new Dish(null, "Lẩu mắm", "Lẩu mắm đặc trưng miền Tây", 370000, 10, "/uploads/1758568277914_H-Lẩu đầu cá hồi_12.jpeg", "HOTPOT", "AVAILABLE"),
            new Dish(null, "Lẩu đầu cá hồi", "Lẩu đầu cá hồi nấu măng chua", 300000, 15, "/uploads/1758568287545_H-Lẩu bắp bò_13.jpeg", "HOTPOT", "AVAILABLE"),
            new Dish(null, "Lẩu bắp bò", "Lẩu bắp bò mềm, ngọt", 350000, 20, "/uploads/1758568297824_H-Lẩu sườn non_14.jpeg", "HOTPOT", "AVAILABLE"),
            new Dish(null, "Lẩu sườn non", "Lẩu sườn non nấu sấu, khoai sọ", 290000, 25, "https://example.com/images/lau_suon_non.jpg", "HOTPOT", "AVAILABLE")
//            new Dish(null, "Lẩu nấm", "Lẩu nấm chay thanh đạm", 250000, 30, "https://example.com/images/lau_nam.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu vịt nấu chao", "Lẩu vịt nấu chao, béo thơm", 320000, 20, "https://example.com/images/lau_vit_chao.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu ốc bươu", "Lẩu ốc bươu chuối đậu, đậm đà", 310000, 15, "https://example.com/images/lau_oc_buou.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu cá kèo", "Lẩu cá kèo lá giang, chua thanh", 280000, 18, "https://example.com/images/lau_ca_keo.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu gà tiềm ớt hiểm", "Lẩu gà tiềm ớt hiểm, cay nồng", 340000, 15, "https://example.com/images/lau_ga_ot_hiem.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu cá bớp", "Lẩu cá bớp măng chua, ngọt nước", 360000, 12, "https://example.com/images/lau_ca_bop.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu kim chi", "Lẩu kim chi Hàn Quốc, chua cay", 320000, 25, "https://example.com/images/lau_kim_chi.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu ghẹ", "Lẩu ghẹ tươi, ngọt nước", 450000, 10, "https://example.com/images/lau_ghe.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu tôm hùm", "Lẩu tôm hùm, sang trọng, đẳng cấp", 950000, 5, "https://example.com/images/lau_tom_hum.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu hải sản chua ngọt", "Lẩu hải sản chua ngọt, dễ ăn", 380000, 15, "https://example.com/images/lau_hai_san_chua_ngot.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu cá diêu hồng", "Lẩu cá diêu hồng nấu măng chua", 280000, 20, "https://example.com/images/lau_ca_dieu_hong.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu lòng", "Lẩu lòng thập cẩm, giòn, dai", 270000, 18, "https://example.com/images/lau_long.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu gà thuốc bắc", "Lẩu gà thuốc bắc, bồi bổ sức khỏe", 300000, 20, "https://example.com/images/lau_ga_thuoc_bac.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu đuôi bò", "Lẩu đuôi bò hầm, mềm, bổ", 350000, 15, "https://example.com/images/lau_duoi_bo.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu lươn", "Lẩu lươn nấu chua cay", 310000, 10, "https://example.com/images/lau_luon.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu sườn sụn", "Lẩu sườn sụn giòn, sần sật", 290000, 25, "https://example.com/images/lau_suon_sun.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu ốc", "Lẩu ốc, bún ốc, thơm ngon", 280000, 20, "https://example.com/images/lau_oc.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu chả cá", "Lẩu chả cá, chả cá dai ngon", 320000, 15, "https://example.com/images/lau_cha_ca.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu gà ác", "Lẩu gà ác tiềm, bổ dưỡng", 330000, 10, "https://example.com/images/lau_ga_ac.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu đầu cá bống", "Lẩu đầu cá bống, ngọt nước", 270000, 15, "https://example.com/images/lau_dau_ca_bong.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu gà lá é", "Lẩu gà lá é, đặc sản Đà Lạt", 350000, 20, "https://example.com/images/lau_ga_la_e.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu hải sản chua cay", "Lẩu hải sản chua cay kiểu Thái", 390000, 18, "https://example.com/images/lau_hai_san_chua_cay.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu chao", "Lẩu chao, béo, đậm đà", 290000, 15, "https://example.com/images/lau_chao.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu cá chình", "Lẩu cá chình măng chua", 420000, 10, "https://example.com/images/lau_ca_chinh.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu trâu nhúng mẻ", "Lẩu trâu nhúng mẻ, chua thanh", 380000, 15, "https://example.com/images/lau_trau.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu thập cẩm nấm", "Lẩu thập cẩm với nhiều loại nấm", 310000, 20, "https://example.com/images/lau_thap_cam_nam.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu cá linh", "Lẩu cá linh bông điên điển, đặc sản", 350000, 12, "https://example.com/images/lau_ca_linh.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu lươn măng chua", "Lẩu lươn nấu măng chua", 300000, 15, "https://example.com/images/lau_luon_mang_chua.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu bạch tuộc", "Lẩu bạch tuộc, giòn sần sật", 340000, 18, "https://example.com/images/lau_bach_tuoc.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu lòng bò", "Lẩu lòng bò, thơm béo", 320000, 20, "https://example.com/images/lau_long_bo.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu vịt hầm sả", "Lẩu vịt hầm sả, thơm lừng", 300000, 25, "https://example.com/images/lau_vit_sa.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu cua", "Lẩu cua đồng, vị ngọt tự nhiên", 380000, 15, "https://example.com/images/lau_cua.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu gà ta lá giang", "Lẩu gà ta lá giang chua thanh", 290000, 20, "https://example.com/images/lau_ga_la_giang.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu bò viên", "Lẩu bò viên, thịt bò viên dai, giòn", 280000, 25, "https://example.com/images/lau_bo_vien.jpg", "HOTPOT", "AVAILABLE"),
//            new Dish(null, "Lẩu hải sản chua ngọt", "Lẩu hải sản chua ngọt", 380000, 15, "https://example.com/images/lau_hai_san_chua_ngot.jpg", "HOTPOT", "AVAILABLE")
        ));

        // ================== 🍟 SNACK (50 món) ==================
        dishes.addAll(Arrays.asList(
            new Dish(null, "Khoai tây chiên", "Khoai tây chiên giòn, ăn kèm tương ớt", 35000, 150, "/uploads/1758639380380_S_khoai tây chiên_1.jpeg", "SNACK", "AVAILABLE"),
            new Dish(null, "Bánh tráng trộn", "Bánh tráng trộn khô bò, xoài, rau răm", 25000, 100, "/uploads/1758639535378_S_bánh tráng trộn_2.jpeg", "SNACK", "AVAILABLE"),
            new Dish(null, "Bánh tráng nướng", "Bánh tráng nướng trứng cút, phô mai", 30000, 80, "/uploads/1758639609372_S_Bánh tráng nướng_3.jpeg", "SNACK", "AVAILABLE"),
            new Dish(null, "Ngô chiên", "Ngô chiên bơ, giòn, béo", 30000, 120, "/uploads/1758639635127_S_Ngô chiên_4.jpeg", "SNACK", "AVAILABLE"),
            new Dish(null, "Bắp rang bơ", "Bắp rang bơ caramel ngọt lịm", 25000, 150, "/uploads/1758639645261_S_Bắp rang bơ_5.jpeg", "SNACK", "AVAILABLE"),
            new Dish(null, "Chân gà sả tắc", "Chân gà ngâm sả tắc, giòn, chua, cay", 50000, 70, "/uploads/1758639658843_S_Chân gà sả tắc_6.jpeg", "SNACK", "AVAILABLE"),
            new Dish(null, "Khô gà lá chanh", "Khô gà lá chanh, cay, thơm", 60000, 50, "/uploads/1758639667870_S_Khô gà lá chanh_7.jpeg", "SNACK", "AVAILABLE"),
            new Dish(null, "Khô bò", "Khô bò miếng, ăn vặt", 70000, 40, "/uploads/1758639679618_S_Khô bò_8.jpeg", "SNACK", "AVAILABLE"),
            new Dish(null, "Bánh khoai lang chiên", "Bánh khoai lang chiên giòn, ngọt", 30000, 100, "/uploads/1758639702234_S_Bánh khoai lang chiên_9.jpeg", "SNACK", "AVAILABLE"),
            new Dish(null, "Bánh chuối chiên", "Bánh chuối chiên giòn, thơm", 35000, 90, "/uploads/1758639713266_S_Bánh chuối chiên_10.jpeg", "SNACK", "AVAILABLE"),
            new Dish(null, "Bánh Pía", "Bánh Pía sầu riêng", 20000, 100, "/uploads/1758639725084_S_Bánh Pía_11.jpeg", "SNACK", "AVAILABLE"),
            new Dish(null, "Bánh bò thốt nốt", "Bánh bò thốt nốt, mềm, dai", 25000, 80, "/uploads/1758639735274_S_Bánh bò thốt nốt_12.jpeg", "SNACK", "AVAILABLE"),
            new Dish(null, "Bánh bột lọc", "Bánh bột lọc nhân tôm thịt", 40000, 70, "/uploads/1758639746040_S_Bánh bột lọc_13.jpeg", "SNACK", "AVAILABLE"),
            new Dish(null, "Bánh bèo chén", "Bánh bèo chén, ăn kèm tôm cháy", 45000, 60, "/uploads/1758639757284_S_Bánh bèo chén_14.jpeg", "SNACK", "AVAILABLE"),
            new Dish(null, "Bánh hỏi chả giò", "Bánh hỏi chả giò, rau sống", 50000, 50, "/uploads/1758639773217_S_Bánh hỏi chả giò_15.jpeg", "SNACK", "AVAILABLE")
//            new Dish(null, "Bánh mì cay", "Bánh mì cay Hải Phòng", 20000, 100, "https://example.com/images/banh_mi_cay.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Bánh phồng tôm", "Bánh phồng tôm chiên, giòn", 30000, 120, "https://example.com/images/banh_phong_tom.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Bánh đa cua", "Bánh đa cua, đặc sản Hải Phòng", 55000, 40, "https://example.com/images/banh_da_cua.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Bánh gân", "Bánh gân, giòn, dai", 35000, 80, "https://example.com/images/banh_gan.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Bánh mì chảo", "Bánh mì chảo nóng, đầy đủ", 60000, 50, "https://example.com/images/banh_mi_chao.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Bánh ướt", "Bánh ướt chả giò, rau sống", 45000, 60, "https://example.com/images/banh_uot.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Bún đậu mắm tôm", "Bún đậu mắm tôm, đầy đủ", 65000, 40, "https://example.com/images/bun_dau.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Trứng cút lộn", "Trứng cút lộn xào me, béo, chua", 35000, 70, "https://example.com/images/trung_cut_lon.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Phô mai que", "Phô mai que chiên, giòn, kéo sợi", 40000, 90, "https://example.com/images/pho_mai_que.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Cá viên chiên", "Cá viên chiên, xúc xích, bò viên", 50000, 80, "https://example.com/images/ca_vien_chien.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Mì tôm chanh", "Mì tôm chanh, chua, cay, giòn", 25000, 100, "https://example.com/images/mi_tom_chanh.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Bánh gạo lắc phô mai", "Bánh gạo lắc phô mai, giòn, béo", 45000, 60, "https://example.com/images/banh_gao_lac_pho_mai.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Ốc luộc", "Ốc luộc, chấm mắm gừng", 50000, 50, "https://example.com/images/oc_luoc.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Ngao hấp sả", "Ngao hấp sả, thơm, ngọt", 60000, 40, "https://example.com/images/ngao_hap_sa.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Sụn gà chiên mắm", "Sụn gà chiên mắm, giòn, đậm vị", 70000, 35, "https://example.com/images/sun_ga_chien_mam.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Gỏi sứa", "Gỏi sứa, giòn, mát", 55000, 45, "https://example.com/images/goi_sua.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Phở cuốn", "Phở cuốn thịt bò, rau sống", 50000, 60, "https://example.com/images/pho_cuon.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Bánh chuối nướng", "Bánh chuối nướng, thơm, ngọt", 30000, 70, "https://example.com/images/banh_chuoi_nuong.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Bánh ngô nướng", "Bánh ngô nướng, thơm lừng", 25000, 80, "https://example.com/images/banh_ngo_nuong.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Bánh khoai mỡ", "Bánh khoai mỡ chiên, béo, bùi", 35000, 90, "https://example.com/images/banh_khoai_mo.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Bánh rán lúc lắc", "Bánh rán lúc lắc, nhân đậu xanh", 20000, 120, "https://example.com/images/banh_ran_luc_lac.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Bánh đúc nóng", "Bánh đúc nóng, ăn kèm thịt băm", 45000, 50, "https://example.com/images/banh_duc_nong.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Bún chả", "Bún chả, đặc sản Hà Nội", 60000, 40, "https://example.com/images/bun_cha.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Nem lụi", "Nem lụi nướng, cuốn bánh tráng", 55000, 55, "https://example.com/images/nem_lui.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Bánh mì bơ sữa", "Bánh mì nướng bơ sữa, ngọt béo", 30000, 100, "https://example.com/images/banh_mi_bo_sua.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Thịt bò khô", "Thịt bò khô miếng, cay, dai", 70000, 40, "https://example.com/images/thit_bo_kho.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Mực khô nướng", "Mực khô nướng, chấm tương ớt", 80000, 30, "https://example.com/images/muc_kho_nuong.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Bánh bột lọc chiên", "Bánh bột lọc chiên giòn, nhân tôm thịt", 40000, 70, "https://example.com/images/banh_bot_loc_chien.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Bánh chuối sấy dẻo", "Bánh chuối sấy dẻo, ngọt tự nhiên", 35000, 90, "https://example.com/images/banh_chuoi_say.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Cơm cháy chà bông", "Cơm cháy giòn, chà bông mặn ngọt", 50000, 60, "https://example.com/images/com_chay.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Snack rong biển", "Snack rong biển, giòn, mặn", 25000, 150, "https://example.com/images/snack_rong_bien.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Mì gói xào trứng", "Mì gói xào trứng, rau củ", 40000, 80, "https://example.com/images/mi_xao_trung.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Bắp xào bơ", "Bắp xào bơ tép khô, thơm, béo", 30000, 90, "https://example.com/images/bap_xao_bo.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Há cảo chiên", "Há cảo chiên giòn, nhân tôm thịt", 45000, 70, "https://example.com/images/ha_cao_chien.jpg", "SNACK", "AVAILABLE"),
//            new Dish(null, "Bánh crepe sầu riêng", "Bánh crepe sầu riêng, kem tươi", 60000, 50, "https://example.com/images/crepe_sau_rieng.jpg", "SNACK", "AVAILABLE")
        ));

        // ================== 🍰 DESSERT (50 món) ==================
        dishes.addAll(Arrays.asList(
            new Dish(null, "Chè thái sầu riêng", "Chè thái sầu riêng, béo ngậy", 45000, 70, "/uploads/1758639800950_D_Chè thái sầu riêng_1.jpeg", "DESSERT", "AVAILABLE"),
            new Dish(null, "Bánh flan caramel", "Bánh flan mềm, mịn, vị caramel", 30000, 100, "/uploads/1758639809152_D_Bánh flan caramel_2.jpeg", "DESSERT", "AVAILABLE"),
            new Dish(null, "Kem dừa", "Kem dừa béo, thơm, ăn kèm dừa sấy", 40000, 80, "/uploads/1758639817710_D_Kem dừa_3.jpeg", "DESSERT", "AVAILABLE"),
            new Dish(null, "Rau câu dừa", "Rau câu dừa thơm mát, giải nhiệt", 35000, 90, "/uploads/1758639825578_D_Râu câu dừa_4.jpeg", "DESSERT", "AVAILABLE"),
            new Dish(null, "Chè ba màu", "Chè ba màu, nước cốt dừa", 25000, 120, "/uploads/1758639835665_D_chè ba màu_5.jpeg", "DESSERT", "AVAILABLE"),
            new Dish(null, "Sữa chua dẻo", "Sữa chua dẻo, ăn kèm topping", 30000, 150, "/uploads/1758639844421_D_Sữa chua dẻo_6.jpeg", "DESSERT", "AVAILABLE"),
            new Dish(null, "Bánh su kem", "Bánh su kem nhân kem trứng", 20000, 200, "/uploads/1758639854265_D_Bánh su kem_7.jpeg", "DESSERT", "AVAILABLE"),
            new Dish(null, "Bánh tiramisu", "Bánh tiramisu, vị cà phê", 60000, 50, "/uploads/1758639862569_D_Bánh tiramisu_8.jpeg", "DESSERT", "AVAILABLE"),
            new Dish(null, "Bánh mousse chanh dây", "Bánh mousse chanh dây, chua ngọt", 55000, 60, "/uploads/1758639876339_D_Bánh mousse chanh dây_9.jpeg", "DESSERT", "AVAILABLE"),
            new Dish(null, "Chè đậu xanh", "Chè đậu xanh, đường, dừa", 20000, 100, "/uploads/1758639890589_D_Chè đậu xanh_10.jpeg", "DESSERT", "AVAILABLE"),
            new Dish(null, "Chè bưởi", "Chè bưởi, giòn, sần sật", 25000, 80, "/uploads/1758639902292_D_chè bưởi_11.jpeg", "DESSERT", "AVAILABLE"),
            new Dish(null, "Chè sen", "Chè hạt sen, đường phèn", 30000, 70, "/uploads/1758639911824_D_chè sen_12.jpeg", "DESSERT", "AVAILABLE"),
            new Dish(null, "Chè khúc bạch", "Chè khúc bạch, nhãn, hạnh nhân", 40000, 50, "/uploads/1758639920407_D_chè khúc bạch_13.jpeg", "DESSERT", "AVAILABLE"),
            new Dish(null, "Bánh kem", "Bánh kem, nhiều vị, trang trí", 50000, 30, "/uploads/1758639930038_D_bánh kem_14.jpeg", "DESSERT", "AVAILABLE"),
            new Dish(null, "Bánh cupcake", "Bánh cupcake nhỏ, dễ thương", 30000, 100, "/uploads/1758639939726_D_Bánh cupcake_15.jpeg", "DESSERT", "AVAILABLE")
//            new Dish(null, "Kem ốc quế", "Kem ốc quế, nhiều vị", 20000, 150, "https://example.com/images/kem_oc_que.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Kem trà xanh", "Kem trà xanh matcha, thơm", 35000, 80, "https://example.com/images/kem_tra_xanh.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Kem vani", "Kem vani, đơn giản, ngon", 30000, 100, "https://example.com/images/kem_vani.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Bánh dừa nướng", "Bánh dừa nướng, giòn, thơm", 25000, 120, "https://example.com/images/banh_dua_nuong.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Bánh bông lan", "Bánh bông lan mềm, xốp", 30000, 90, "https://example.com/images/banh_bong_lan.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Chè trôi nước", "Chè trôi nước, nhân đậu xanh, đường", 25000, 80, "https://example.com/images/che_troi_nuoc.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Chè khoai dẻo", "Chè khoai dẻo, đường, cốt dừa", 35000, 60, "https://example.com/images/che_khoai_deo.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Chè đậu đen", "Chè đậu đen, giải nhiệt", 20000, 100, "https://example.com/images/che_dau_den.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Sương sáo hạt é", "Sương sáo hạt é, thanh mát", 25000, 90, "https://example.com/images/suong_sao_hat_e.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Bánh bò nướng", "Bánh bò nướng, mềm, xốp", 30000, 70, "https://example.com/images/banh_bo_nuong.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Bánh phô mai", "Bánh phô mai, béo, ngậy", 60000, 50, "https://example.com/images/banh_pho_mai.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Bánh mochi kem", "Bánh mochi kem lạnh, nhân kem", 45000, 60, "https://example.com/images/mochi_kem.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Kem chuối", "Kem chuối, dừa khô, đậu phộng", 30000, 80, "https://example.com/images/kem_chuoi.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Kem bơ", "Kem bơ, béo, ngọt", 40000, 70, "https://example.com/images/kem_bo.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Bánh crepe", "Bánh crepe mỏng, nhân kem", 35000, 90, "https://example.com/images/banh_crepe.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Kem socola", "Kem socola, béo, đậm vị", 30000, 100, "https://example.com/images/kem_socola.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Kem dâu", "Kem dâu, chua ngọt", 30000, 90, "https://example.com/images/kem_dau.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Kem chuối", "Kem chuối, đậu phộng, dừa", 25000, 120, "https://example.com/images/kem_chuoi.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Bánh macaron", "Bánh macaron, nhiều màu, ngọt", 60000, 50, "https://example.com/images/macaron.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Bánh Donut", "Bánh Donut, nhiều vị", 30000, 100, "https://example.com/images/donut.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Bánh rán Doremon", "Bánh rán Doremon, nhân đậu đỏ", 35000, 80, "https://example.com/images/banh_ran_doremon.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Chè xoài", "Chè xoài, sữa chua, thạch", 40000, 70, "https://example.com/images/che_xoai.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Bánh mì kem", "Bánh mì kẹp kem lạnh", 30000, 90, "https://example.com/images/banh_mi_kem.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Bánh flan lá dứa", "Bánh flan lá dứa, thơm, mềm", 35000, 80, "https://example.com/images/flan_la_dua.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Sữa chua nếp cẩm", "Sữa chua nếp cẩm, béo, bùi", 40000, 70, "https://example.com/images/sua_chua_nep_cam.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Kem chiên", "Kem chiên, vỏ giòn, nhân kem", 45000, 60, "https://example.com/images/kem_chien.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Bánh mochi nướng", "Bánh mochi nướng, phô mai", 50000, 50, "https://example.com/images/mochi_nuong.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Bánh khoai lang", "Bánh khoai lang, dừa nạo", 30000, 80, "https://example.com/images/banh_khoai_lang_deo.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Kem cuộn", "Kem cuộn, nhiều vị", 40000, 70, "https://example.com/images/kem_cuon.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Bánh trứng", "Bánh trứng, mềm, xốp", 25000, 100, "https://example.com/images/banh_trung.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Chè sầu riêng", "Chè sầu riêng, thơm, béo", 50000, 50, "https://example.com/images/che_sau_rieng.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Bánh dứa", "Bánh dứa, chua, ngọt", 35000, 70, "https://example.com/images/banh_dua.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Bánh chuối dừa", "Bánh chuối dừa, béo, thơm", 30000, 80, "https://example.com/images/banh_chuoi_dua.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Bánh crepe sầu riêng", "Bánh crepe sầu riêng, kem tươi", 60000, 50, "https://example.com/images/crepe_sau_rieng.jpg", "DESSERT", "AVAILABLE"),
//            new Dish(null, "Kem bơ dừa", "Kem bơ dừa, béo ngậy", 45000, 60, "https://example.com/images/kem_bo_dua.jpg", "DESSERT", "AVAILABLE")
        ));

        // ================== 🥤 DRINK (50 món) ==================
        dishes.addAll(Arrays.asList(
            new Dish(null, "Coca Cola", "Nước ngọt có ga", 20000, 200, "/uploads/1758640006145_DR_Coca Cola_1.jpeg", "DRINK", "AVAILABLE"),
            new Dish(null, "Trà đào cam sả", "Trà đào cam sả, thơm, thanh", 45000, 150, "/uploads/1758640514131_DR_Trà đào cam sả_3.jpeg", "DRINK", "AVAILABLE"),
            new Dish(null, "Nước cam ép", "Nước cam tươi ép", 35000, 100, "/uploads/1758640037737_DR_Nước cam ép_2.jpeg", "DRINK", "AVAILABLE"),
            new Dish(null, "Nước chanh", "Nước chanh tươi, giải khát", 25000, 120, "/uploads/1758640050602_DR_Nước chanh_4.jpeg", "DRINK", "AVAILABLE"),
            new Dish(null, "Sinh tố bơ", "Sinh tố bơ, béo, bổ dưỡng", 50000, 80, "/uploads/1758640059680_DR_Sinh tố bơ_5.jpeg", "DRINK", "AVAILABLE"),
            new Dish(null, "Sinh tố dâu", "Sinh tố dâu tươi, chua ngọt", 45000, 90, "/uploads/1758640068546_DR_Sinh tố dâu_6.jpeg", "DRINK", "AVAILABLE"),
            new Dish(null, "Sữa chua đá xay", "Sữa chua đá xay, mát lạnh", 40000, 100, "/uploads/1758640079647_DR_Sữa chua đá xay_7.jpeg", "DRINK", "AVAILABLE"),
            new Dish(null, "Trà sữa trân châu", "Trà sữa trân châu đường đen", 50000, 150, "/uploads/1758640098744_DR_Trà sữa trân châu_8.jpeg", "DRINK", "AVAILABLE"),
            new Dish(null, "Cà phê sữa đá", "Cà phê sữa đá, đậm vị", 30000, 120, "/uploads/1758640107792_DR_Cà phê sữa đá_9.jpeg", "DRINK", "AVAILABLE"),
            new Dish(null, "Cà phê đen đá", "Cà phê đen đá, đắng, mạnh", 25000, 100, "/uploads/1758640117476_DR_Cà phê đen đá_10.jpeg", "DRINK", "AVAILABLE"),
            new Dish(null, "Nước dừa tươi", "Nước dừa tươi, mát, giải khát", 30000, 150, "https://example.com/images/nuoc_dua.jpgpg", "DRINK", "AVAILABLE"),
            new Dish(null, "Trà chanh", "Trà chanh, chua, ngọt", 25000, 180, "/uploads/1758640144020_DR_Trà chanh_12.jpeg", "DRINK", "AVAILABLE"),
            new Dish(null, "Nước ép dứa", "Nước ép dứa tươi", 35000, 90, "/uploads/1758640155109_DR_Nước ép dứa_13.jpeg", "DRINK", "AVAILABLE"),
            new Dish(null, "Nước ép dưa hấu", "Nước ép dưa hấu, ngọt mát", 35000, 100, "/uploads/1758640167108_DR_Nước ép dưa hấu_14.jpeg", "DRINK", "AVAILABLE"),
            new Dish(null, "Nước ép táo", "Nước ép táo, thơm, ngon", 40000, 80, "/uploads/1758640175882_DR_Nước ép táo_15.jpeg", "DRINK", "AVAILABLE"),
            new Dish(null, "Nước ép ổi", "Nước ép ổi, đậm vị", 35000, 70, "/uploads/1758640218129_DR_nước ép ổi_16.jpeg", "DRINK", "AVAILABLE")
//            new Dish(null, "Soda chanh dây", "Soda chanh dây, chua, ngọt", 40000, 100, "https://example.com/images/soda_chanh_day.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Soda việt quất", "Soda việt quất, màu sắc đẹp", 45000, 80, "https://example.com/images/soda_viet_quat.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Sữa tươi trân châu đường đen", "Sữa tươi trân châu đường đen", 45000, 120, "https://example.com/images/sua_tuoi_tran_chau.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Hồng trà sữa", "Hồng trà sữa, vị trà nhẹ", 40000, 150, "https://example.com/images/hong_tra_sua.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Trà sữa matcha", "Trà sữa matcha, vị trà xanh", 45000, 100, "https://example.com/images/tra_sua_matcha.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Trà sữa khoai môn", "Trà sữa khoai môn, bùi, thơm", 45000, 90, "https://example.com/images/tra_sua_khoai_mon.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Nước ép cà rốt", "Nước ép cà rốt, tốt cho mắt", 35000, 80, "https://example.com/images/nuoc_ep_ca_rot.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Nước ép cần tây", "Nước ép cần tây, detox", 40000, 70, "https://example.com/images/nuoc_ep_can_tay.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Sinh tố xoài", "Sinh tố xoài, ngọt, thơm", 45000, 90, "https://example.com/images/sinh_to_xoai.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Sinh tố dứa", "Sinh tố dứa, chua ngọt", 40000, 80, "https://example.com/images/sinh_to_dua.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Sữa đậu nành", "Sữa đậu nành, nguyên chất", 20000, 150, "https://example.com/images/sua_dau_nanh.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Trà xanh", "Trà xanh, thanh mát", 30000, 100, "https://example.com/images/tra_xanh.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Trà gừng nóng", "Trà gừng nóng, tốt cho sức khỏe", 25000, 70, "https://example.com/images/tra_gung.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Sô cô la nóng", "Sô cô la nóng, ngọt ngào", 40000, 80, "https://example.com/images/socola_nong.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Nước ép lựu", "Nước ép lựu tươi, chua ngọt", 50000, 60, "https://example.com/images/nuoc_ep_luu.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Nước ép dâu tây", "Nước ép dâu tây, thơm ngon", 45000, 70, "https://example.com/images/nuoc_ep_dau_tay.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Nước ép nho", "Nước ép nho, ngọt thanh", 40000, 80, "https://example.com/images/nuoc_ep_nho.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Nước ép bưởi", "Nước ép bưởi, chua, đắng", 35000, 70, "https://example.com/images/nuoc_ep_buoi.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Nước ép bưởi đào", "Nước ép bưởi đào, chua ngọt", 40000, 80, "https://example.com/images/nuoc_ep_buoi_dao.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Nước dứa ép", "Nước dứa ép, thơm, ngon", 35000, 90, "https://example.com/images/nuoc_dua_ep.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Nước ép cam, cà rốt", "Hỗn hợp cam và cà rốt", 40000, 80, "https://example.com/images/nuoc_ep_cam_ca_rot.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Sữa tươi nóng", "Sữa tươi nóng, nguyên kem", 25000, 100, "https://example.com/images/sua_tuoi_nong.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Sữa ca cao", "Sữa ca cao, ngọt, béo", 30000, 90, "https://example.com/images/sua_ca_cao.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Cà phê trứng", "Cà phê trứng, đặc trưng Hà Nội", 45000, 70, "https://example.com/images/ca_phe_trung.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Trà dâu tây", "Trà dâu tây, chua ngọt", 40000, 90, "https://example.com/images/tra_dau_tay.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Trà chanh leo", "Trà chanh leo, thơm", 35000, 100, "https://example.com/images/tra_chanh_leo.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Trà vải", "Trà vải, ngọt, thanh", 40000, 90, "https://example.com/images/tra_vai.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Trà đào", "Trà đào, thơm, giải khát", 40000, 110, "https://example.com/images/tra_dao_rieng.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Nước dừa tắc", "Nước dừa tắc, chua ngọt", 35000, 120, "https://example.com/images/nuoc_dua_tac.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Sinh tố dứa xoài", "Sinh tố dứa xoài, thơm", 50000, 70, "https://example.com/images/sinh_to_dua_xoai.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Sinh tố bơ sầu riêng", "Sinh tố bơ sầu riêng, béo ngậy", 60000, 50, "https://example.com/images/sinh_to_bo_sau_rieng.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Nước chanh leo", "Nước chanh leo, chua, mát", 35000, 90, "https://example.com/images/nuoc_chanh_leo.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Nước ép cà chua", "Nước ép cà chua, tốt cho da", 30000, 80, "https://example.com/images/nuoc_ep_ca_chua.jpg", "DRINK", "AVAILABLE"),
//            new Dish(null, "Nước ép dứa, dưa hấu", "Hỗn hợp dứa và dưa hấu", 40000, 80, "https://example.com/images/nuoc_ep_dua_dua_hau.jpg", "DRINK", "AVAILABLE")
        ));

        dishRepository.saveAll(dishes);
        System.out.println("✅ Đã seed dữ liệu món ăn vào DB!");
    }
}